name: Continuous Integration

on: [pull_request, push]

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Using Dotnet 8
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore

            - name: Test
              run: dotnet test

            - name: Build release
              run: dotnet build -c Release